### ISSUE TITLE
wrong Elasticsearch 2.x download url

### ISSUE THREAD

**Issue by gesellix** [amirkibbar/bilberry#1]
Thanks for the nice plugin!

I tried to use it with the recently released version ES 2.0.0, but the download urls seem to have changed. Instead of `https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.0.0.tar.gz` the new `https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.0.0/elasticsearch-2.0.0.tar.gz` should be correct. Or did I miss some configuration detail?

**Comment by amirkibbar** [comment]
You're right, the URL for elastic 2.0.0 has changed. I've added a simple check to see if the new URL or the old URL needs to be used according to the requested version, seems to be working, please verify (version 0.0.6).

**Comment by gesellix** [comment]
download works now, thanks!
