### ISSUE TITLE
Execute permissions absent for elastic search shell scripts

### ISSUE THREAD

**Issue by kk-manh** [amirkibbar/bilberry#3]
Hi,
One issue I have hit is that after the elastic search archive is extracted, the shell scritps in the bin folder dont have execute permissions. this causes the gradle task to fail.
This happens on *nix systems. I havent tried on Windows yet.

**Comment by amirkibbar** [comment]
Hi,

a recent pull request by @gesellix fixed this issue, Please try the new version (0.0.5) and let me know if it now works for you.

**Comment by kk-manh** [comment]
I am still facing the same issue
"gradle/tools/elastic"): error=13, Permission denied"

The code in ElasticActions.;groovy is attempting to execute the "plugin" shell script
so you need to change
   ant.chmod(file: new File("$home/bin/elasticsearch"), perm: "+x")

TO

   ant.chmod(file: new File("$home/bin/elasticsearch"), perm: "+x")
   ant.chmod(file: new File("$home/bin/plugin"), perm: "+x")

NOTE: Both files will need execute permissions in UNIX systems
