### ISSUE TITLE
attempt to start already installed elastic search 1.5.2 leads to hang

### ISSUE THREAD

**Issue by apa** [amirkibbar/bilberry#6]
I catched situation, that plugin hangs when it tries to startup elastic search second time. Appears that the problem in https://github.com/amirkibbar/bilberry/blob/master/src/main/groovy/ajk/gradle/elastic/ElasticActions.groovy class in method "isDesiredVersion()". 

Method tries to execute external process "${home}/bin/elasticsearch" with parameter "--version". But Elastic Search with version 1.5.2 does not handle parameter '--version'. Instead of that it propose parameter "-v". Here part of output of ES help:
" -v            print elasticsearch version, then exit"
In case of usage '--version' elasticsearch just starts, so method "waitForProcessOutput()" used by plugin just never returns.

I had tested how plugin behaves on my local environment after updating '--version' on '-v' in plugin sourcecode and it works. But I cannot propose that as pull request, because I have no chance does this works on windows (I'm using linux) and whether it works on elastic search with 2.x+ versions.

PS. whether this code in 'isDesiredVersion()' works at all on windows? I had explored elasticsearch.bat and did not find handling of neither '-v' or '--version' options.

**Comment by amirkibbar** [comment]
Hi,

Thank you for reporting this issue. Yes, of course you're right. Working on a solution, in the meantime there's an easy workaround - if you omit the "elasticVersion" from the startElastic {} section, then the default version - 1.5.2 is used, and this isDesiredVersion() is not executed. Yes, that's a lame workaround, but it should work until I find a proper solution.

Thanks,
Amir

**Comment by amirkibbar** [comment]
ok, so it seems that the good people at elastic.io forgot to add a windows script that reports the installed version, had to create one for myself (see ElasticActions.groovy:isDesiredVersion).

Please try and let me know if this new release 0.0.10 fixed the issue.
